### ISSUE TITLE
Placeholder Image

### ISSUE THREAD

**Issue by KunalDev** [timonus/TJImageCache#14]
How to set place holder image?

**Comment by timonus** [comment]
There's no explicit API for placeholder images, however you could assign the `image` to an image view and immediately after call a `TJImageCache` method to set a remote image on it. The image view will show the image you set on it until the remote image loads, which is effectively a placeholder image.

**Comment by KunalDev** [comment]
> There's no explicit API for placeholder images, however you could assign the `image` to an image view and immediately after call a `TJImageCache` method to set a remote image on it. The image view will show the image you set on it until the remote image loads, which is effectively a placeholder image.

I have used below code and it is not working:

imageView.image = [UIImage imageNamed:@"PlaceHolder"];
[imageView tj_setImageURLString:imageURL forceDecompress:NO];

Amy suggestions ?
